---
title: "About the trial"
---

## About the trial

Migraine headache is a painful condition of recurrent moderate to severe head pain associated with nausea, vomiting, photophobia, and sonophobia. The condition is highly prevalent and a significant community health problem with considerable impact on the health care system. The World Health Organization classifies migraine as one of the top twenty leading causes of disability at all ages ~~{World Health Organization, 2001 #4082}.~~ [(1).]{.underline} Data from the Canadian National Longitudinal Survey of Children and Youth suggests that more than 26% of 12 to 13 year olds report headache \"about once a week\" with significant impacts in school, lifestyle, and mental health domains (2). Children and adolescents with migraine rate their quality of life similarly to those with other chronic diseases like rheumatoid arthritis and cancer with impairments in school and social functioning (3). To alleviate the pain and morbidity associated with a migraine attack, drug therapies are often employed including simple analgesics like ibuprofen and migraine-specific medications like sumatriptan. When these treatments fail or in severe, intractable cases, patients and families present to the Emergency Department (ED) with significant implications on resource utilization. The two ED departments in Alberta assess between 500 and 1000 patients each year with headache or migraine (not including those visits related to head injuries). Children are often in significant pain and may receive intravenous therapies such as metoclopramide (Maxeran), prochlorperazine (Stemetil), and ketorolac (Toradol). Some of the most commonly employed medications to treat migraine headache in the ED, however, have not been evaluated for their efficacy and safety in children.

Ketorolac in combination with metoclopramide or prochlorperazine was the most common multi-drug combination used in 36% of ED presentations for migraine across Canada in our national practice variation study (4). The scientific rationale for combining a non-selective non-steroidal anti-inflammatory drug (NSAID) with inhibition of both the cyclooxygenase (COX) 1 and 2 isoenzymes with other migraine therapies is enticing [(5)]{.underline}~~{Straube, 2011, r04304}~~; however, no studies have specifically examined the relative efficacy of the practice. In the outpatient setting, a combination of sumatriptan (the reference drug in the triptan class of migraine-specific serotonin 1b/1d agonists) and naproxen sodium (another non-selective NSAID) has been evaluated. The efficacy of the combined medications was superior to placebo in migraine patients with poor-response to short acting triptans (6). The efficacy and consistency of the response was also observed in two more randomized adult studies (7) and one pediatric study (8). The use of sumatriptan in the ED is not however supported in the adult literature with prochlorperazine showing higher efficacy (9).

**Why would the combination of a non-selective NSAID like naproxen sodium or ketorolac with other migraine therapies improve treatment outcomes?** The benefit of multi-target combinations may be relate to the duration of the migraine and the multiple brain areas involved in sustained pain. It has long been recognized that patients who treat their migraine headaches early at the onset have a better response (10,11). The underlying mechanism for this phenomenon has now been identified. The initiation of migraine pain requires activation of the trigeminal (5th cranial nerve) nociceptive (pain) system. Activation of these sensory fibers within the arachnoid membrane on the surface of the brain produces the first and most common painful manifestation of migraine - the pulsatile headache. With each heartbeat, minor dilation of the cerebral blood vessels produces stretch and a painful activation of the trigeminal fibers known as peripheral sensitization. The second phase in the maintenance of a migraine attack over several hours is the sensitization of trigeminal pain pathways leading to higher brain centers known as central sensitization. The efficacy of medications like the triptans is greater early in the course of a migraine attack when there is only peripheral sensitization and before the onset of central sensitization. Once central sensitization has begun, sometimes hours after the onset of the migraine attack, these same triptan medications are no longer effective. Non-selective NSAIDs like naproxen sodium and ketorolac, however, have been shown to be uniquely effective in the reduction of central sensitization in the animal model of migraine (12,13) and the reduction of migraine pain in adult patients (14) (see attached publication) late in the course of a migraine headache.

The population of patients in the ED is uniquely different from outpatients in that most have developed their migraine headache hours or days before presenting. In our practice variation study, the mean duration of the migraine prior to presenting to the ED was 2 days (4). Including an NSAID when treating a prolonged migraine in the ED may thus increase the therapeutic window and improve outcomes. While many Canadian ED physicians have adopted the practice of combining ketorolac with other migraine therapies, the gold standard assessment of efficacy and safety in a randomized clinical trial has not been applied.
