---
title: "Clinical Trials 101 Course"
---

An analysis of a randomized controlled trial of ketorolac + metoclopramide versus metoclopramide alone.

```{r}
#| echo: false
#| output: false
#| warning: false

library(rsconnect)
library(tidyverse)
library(consort)
library(skimr)
source("keto_migraine_rct.R")

```

```{r}
#| echo: false

set.seed(1001)
N <- 645

sid <- 1:N
randomized <- rep("0", N)
randomized[sample(1:N,54)] <- "1"

exc1 <- rep(NA, N)
exc1[randomized=="0"] <- sample(c("Not meeting inclusion criteria", "Declined to participate",
                                  "Other reasons"), 591, replace = TRUE, prob = c(0.9, 0.06, 0.04))

exc2 <- rep(NA, N)

# randomized[is.na(exc1)] <- "1"

df <- tibble(sid,randomized,exc1)

df_r <- df %>%
  filter(randomized=="1") %>%
  mutate(id=row_number())

out <- consort_plot(data = df,
                    orders = c(sid = "Assessed for eligibility",
                               exc1    = "Excluded",
                               randomized    = "Randomized"),
                    side_box = c("exc1"),
                    labels = c("1" = "Screening", "2" = "Randomization"))

plot(out)


```
